### ISSUE TITLE
Missing links to repos, crates.io

### ISSUE THREAD

**Issue by killercup** [riker-rs/website#1]
I've just found riker by looking at the crates.io homepage, and went to check out <http://riker.rs>.

This site doesn't seem to have any link to the repos on github, and neither do the crates in their Cargo.toml files (so crates.io doesn't link to the code either). As I really enjoy reading the implementation of a library before using it, this was very confusing, especially as all that is needed was a single link to <https://github.com/riker-rs> to find all the goodness :)

**Comment by leenozara** [comment]
Hi @killercup thanks for the comment! I've added the main git repo to the top navigation of the site. Do you think this works best or instead the link to the `riker-rs` organization and then let folks navigate to the individual repositories?

I'm going to leave this issue open to get your feedback but also to get the Cargo.toml files updated on crates.io.

Really appreciate the help!

**Comment by killercup** [comment]
Looks great! If the main repo is also the entry point for most users, this should suffice.

Thinking of typical links for Rust projects, you might also want to link to the API docs somewhere (looks like https://docs.rs/riker already works).

Oh and this again got me scrolling through your website. http://riker.rs/actors/ links to https://github.com/riker-rs/examples/basic -- which is a 404. If you want to link to the `basic` directory in that repo you might also want to link to a specific tag -- so the docs stay consistent across future versions of your lib.

**Comment by leenozara** [comment]
Hi @killercup I've updated the broken links and provided the repository link in Cargo.toml.

I've really appreciated your help review the documentation.

Let me know if you find anything else or if I can close this issue. Thanks!

**Comment by killercup** [comment]
Cool! That's all I have for now :)
