### ISSUE TITLE
Please provide more explanation on messaging

### ISSUE THREAD

**Issue by snnsnn** [riker-rs/website#14]
Please can you elaborate on messaging. 
Can messages can be delivered out of order?
What are the guarantees?
What if Actor A send multiple messages to Actor B?
What if Actor A and Actor B send multiple messages to Actor C?
Thank you.

**Comment by leenozara** [comment]
Good points. The current documentation needs to be expanded and the topics elaborated on. Let's address your questions in an update to the documentation. I can begin to update it in the coming days. And if there's any more updates from you to the content I'll quickly get them reviewed and published.

Thanks @snnsnn !
